import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Book sidebar with auto-generated chapter navigation
  bookSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'chapter-1-introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-2-ros2',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-3-simulation',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-4-isaac',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-5-vla',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-6-capstone',
    },
  ],
};

export default sidebars;
